version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: n8n-mysql
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_mysql_data:/var/lib/mysql
    networks:
      - n8n-network

  n8n:
    image: n8nio/n8n:1.94.0
    container_name: n8n-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "${N8N_PORT-5678}:5678"
    env_file:
      - .env
    environment:
      # Turn on HTTPS
      N8N_PROTOCOL: https
      N8N_SSL_CERT: /home/node/.n8n/certs/n8n_hattek_net_cert.pem
      N8N_SSL_KEY:  /home/node/.n8n/certs/n8n_hattek_net_key.pem

      # Configure n8n app to use MYSQL
      DB_TYPE: mysqldb 
      DB_MYSQLDB_HOST: mysql
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_DATABASE: ${MYSQL_DATABASE}
      DB_MYSQLDB_USER: ${MYSQL_USER}
      DB_MYSQLDB_PASSWORD: ${MYSQL_PASSWORD}

      # Basic authentication
      BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}

      # Other settings
      GENERIC_TIMEZONE: Asia/Bangkok
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      WEBHOOK_TUNNEL_URL: https://n8n.hattek.net/

    volumes:
      - n8n_data:/home/node/.n8n
      - ./certs:/home/node/.n8n/certs:ro
    networks:
      - n8n-network

volumes:
  n8n_mysql_data:
  n8n_data:

networks:
  n8n-network:
    driver: bridge
